/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Capa_Presentacion;

import java.awt.*;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author dario
 */
public class B_BusquedaDeEventos extends javax.swing.JFrame {

    // --- VARIABLES DE ARQUITECTURA ---
    private CompraBoletoFacade fachada;
    private C_ControlTransaccional controlNavegacion;
    private JPanel panelContenedorTarjetas;

    public B_BusquedaDeEventos() {
        initComponents();
    }

    public B_BusquedaDeEventos(CompraBoletoFacade fachada, C_ControlTransaccional controlNavegacion) {
        initComponents(); // Carga la interfaz gráfica de NetBeans
        
        this.fachada = fachada;
        this.controlNavegacion = controlNavegacion;
        
        configurarBuscadorYTarjetas();
        cargarTarjetas(""); // Carga todos los eventos al iniciar
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        F_Eventos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        scrollTarjetas = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 249, 245));

        jPanel2.setBackground(new java.awt.Color(15, 120, 209));

        jLabel1.setBackground(new java.awt.Color(248, 249, 245));
        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 249, 245));
        jLabel1.setText("TickUp");

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 249, 250));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario (1).png"))); // NOI18N
        jLabel2.setText("Mis Boletos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(15, 120, 209));
        jLabel3.setText("Eventos mas Recientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTarjetas)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(F_Eventos, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 170, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(F_Eventos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTarjetas, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B_BusquedaDeEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B_BusquedaDeEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B_BusquedaDeEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B_BusquedaDeEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B_BusquedaDeEventos().setVisible(true);
            }
        });
    }


    private void configurarBuscadorYTarjetas() {
        // 1. Configurar el panel interno que irá dentro de tu scrollTarjetas
        panelContenedorTarjetas = new JPanel();
        panelContenedorTarjetas.setLayout(new GridLayout(0, 1, 10, 10)); // Crece hacia abajo
        panelContenedorTarjetas.setBackground(new Color(248, 249, 245)); 
        
        // Asignamos el panel al ScrollPane que dibujaste en NetBeans
        scrollTarjetas.setViewportView(panelContenedorTarjetas);
        scrollTarjetas.getVerticalScrollBar().setUnitIncrement(16);

        // 2. Darle vida al buscador F_Eventos en tiempo real
        F_Eventos.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                // Cada vez que el usuario teclea, se filtra y recarga
                cargarTarjetas(F_Eventos.getText());
            }
        });
    }

    private void cargarTarjetas(String filtro) {
        // Limpiamos el contenedor
        panelContenedorTarjetas.removeAll();

        // Pedimos los datos puros a la Fachada
        if (fachada != null) {
            List<String[]> eventos = fachada.obtenerEventosFiltradosParaTarjetas(filtro);

            if (eventos.isEmpty()) {
                panelContenedorTarjetas.add(new JLabel("  No se encontraron eventos..."));
            } else {
                for (String[] ev : eventos) {
                    // ev[0] = ID, ev[1] = Nombre, ev[2] = Descripcion, ev[3] = Fecha
                    JPanel tarjeta = crearTarjetaVisual(ev[0], ev[1], ev[2], ev[3]);
                    panelContenedorTarjetas.add(tarjeta);
                }
            }
        }

        // Refrescamos la pantalla gráficamente
        panelContenedorTarjetas.revalidate();
        panelContenedorTarjetas.repaint();
    }

    private JPanel crearTarjetaVisual(String idEvento, String nombre, String descripcion, String fecha) {
        JPanel tarjeta = new JPanel(new BorderLayout(15, 10));
        tarjeta.setBackground(Color.WHITE);
        tarjeta.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(200, 200, 200), 1, true),
            BorderFactory.createEmptyBorder(15, 15, 15, 15)
        ));

        // Panel de información (Izquierda)
        JPanel panelInfo = new JPanel(new GridLayout(3, 1));
        panelInfo.setBackground(Color.WHITE);
        
        JLabel lblNombre = new JLabel(nombre);
        lblNombre.setFont(new Font("Ebrima", Font.BOLD, 18));
        lblNombre.setForeground(new Color(15, 120, 209));
        
        JLabel lblDesc = new JLabel(descripcion);
        lblDesc.setFont(new Font("Ebrima", Font.PLAIN, 12));
        lblDesc.setForeground(Color.DARK_GRAY);
        
        JLabel lblFecha = new JLabel("Fecha: " + fecha);
        lblFecha.setFont(new Font("Ebrima", Font.BOLD, 12));

        panelInfo.add(lblNombre);
        panelInfo.add(lblDesc);
        panelInfo.add(lblFecha);

        // Botón de Comprar (Derecha)
        JButton btnComprar = new JButton("Comprar");
        btnComprar.setBackground(new Color(15, 120, 209));
        btnComprar.setForeground(Color.WHITE);
        btnComprar.setFont(new Font("Ebrima", Font.BOLD, 14));
        btnComprar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        // EVENTO DEL BOTÓN: Le avisa al Control Transaccional que cambie de pantalla
        btnComprar.addActionListener(e -> {
            if (controlNavegacion != null) {
                // Aquí el control cierra esta ventana y abre B_MapaDeZonas pasándole el idEvento
                controlNavegacion.irAMapaZonas(this, idEvento); 
            }
        });

        tarjeta.add(panelInfo, BorderLayout.CENTER);
        tarjeta.add(btnComprar, BorderLayout.EAST);

        return tarjeta;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField F_Eventos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane scrollTarjetas;
    // End of variables declaration//GEN-END:variables
}
